#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Ariel Schiavoni"
email = "arielschiavoni@gmail.com"

[ui]
editor = "nvim"
default-command = ["log"]
diff-formatter = ["delta", "--side-by-side", "$left", "$right", "--width=$width"]
# diff-formatter = ["difft", "--color=always", "$left", "$right"]
