[tools]
bun = "1.3"
deno = "2.2"
go = "1.24"
node = "22"
"npm:prettier" = "latest"
"npm:aws-cdk" = "latest"
"npm:verdaccio" = "latest"

[env]
# https://mise.jdx.dev/mise-cookbook/nodejs.html#add-node-modules-binaries-to-the-path
_.path = ['{{config_root}}/node_modules/.bin']

[settings]
idiomatic_version_file_enable_tools = ["node"]
